//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18051
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibraryBusinessMonitor.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:33596/A%E5%90%8E%E5%8F%B0/pingtaiservices/ws2013.asmx")]
        public string ClassLibraryBusinessMonitor_bendi2013_fm8844_com_ws2013 {
            get {
                return ((string)(this["ClassLibraryBusinessMonitor_bendi2013_fm8844_com_ws2013"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.0.26:777/pingtaiservices/ws2013.asmx")]
        public string ClassLibraryBusinessMonitor_ceshi2013_fm8844_com_ws2013 {
            get {
                return ((string)(this["ClassLibraryBusinessMonitor_ceshi2013_fm8844_com_ws2013"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://pt.fm8844.com/pingtaiservices/ws2013.asmx")]
        public string ClassLibraryBusinessMonitor_pt2013_fm8844_com_ws2013 {
            get {
                return ((string)(this["ClassLibraryBusinessMonitor_pt2013_fm8844_com_ws2013"]));
            }
        }
    }
}
