<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:apachesoap="http://xml.apache.org/xml-soap" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:intf="http://192.168.100.10:8080/forever/infocenter/CallCenterAddOrder1.jws" xmlns:impl="http://192.168.100.10:8080/forever/infocenter/CallCenterAddOrder1.jws" targetNamespace="http://192.168.100.10:8080/forever/infocenter/CallCenterAddOrder1.jws" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <wsdl:types />
  <wsdl:message name="addOrderResponse">
    <wsdl:part name="addOrderReturn" type="xsd:string" />
  </wsdl:message>
  <wsdl:message name="addOrderRequest">
    <wsdl:part name="orderXml" type="xsd:string" />
    <wsdl:part name="Flag" type="xsd:string" />
  </wsdl:message>
  <wsdl:portType name="CallCenterAddOrder1">
    <wsdl:operation name="addOrder" parameterOrder="orderXml Flag">
      <wsdl:input name="addOrderRequest" message="impl:addOrderRequest" />
      <wsdl:output name="addOrderResponse" message="impl:addOrderResponse" />
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="CallCenterAddOrder1SoapBinding" type="impl:CallCenterAddOrder1">
    <wsdlsoap:binding transport="http://schemas.xmlsoap.org/soap/http" style="rpc" />
    <wsdl:operation name="addOrder">
      <wsdlsoap:operation soapAction="" />
      <wsdl:input name="addOrderRequest">
        <wsdlsoap:body use="encoded" namespace="http://DefaultNamespace" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" />
      </wsdl:input>
      <wsdl:output name="addOrderResponse">
        <wsdlsoap:body use="encoded" namespace="http://192.168.100.10:8080/forever/infocenter/CallCenterAddOrder1.jws" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" />
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="CallCenterAddOrder1Service">
    <wsdl:port name="CallCenterAddOrder1" binding="impl:CallCenterAddOrder1SoapBinding">
      <wsdlsoap:address location="http://192.168.100.10:8080/forever/infocenter/CallCenterAddOrder1.jws" />
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>